# Generated by Django 2.2 on 2020-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publish_timestamp', models.DateTimeField()),
                ('video_id', models.CharField(max_length=20)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
